# Generated by IBM TransformationAdvisor
# Mon Jun 13 06:41:53 UTC 2022

# FROM ibmcom/websphere-traditional:8.5.5.17-ubi
# FROM icr.io/appcafe/websphere-traditional:8.5.5.22-ubi8-ppc64le
FROM icr.io/appcafe/websphere-traditional:8.5.5.22-ubi8

# put app and scripts and properties in /work/config
# put external library (e.g db driver) in /work/config/lib
COPY --chown=was:root daytrader-ear-2.1-snapshot.ear /work/config/daytrader-ear-2.1-snapshot.ear
COPY --chown=was:root ./src/config /work/config
COPY --chown=was:root ./lib /work/config/lib
RUN /work/configure.sh
